title: Charles Do's Homepage
page-top-title: Charles Do
top-section-bg-text: Stay focused and never give up
home-subtitle: Charles Do&ensp;|&ensp;杜文辉
copyright-text: '&copy; Charles Do 2023-2025. All Rights Reserved.'